// swift-tools-version:4.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "Codex",
    products: [
        // Products define the executables and libraries produced by a package, and make them visible to other packages.
        .library(
            name: "Codex",
            targets: ["Codex", "SwiftLang"]),
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
            name: "Codex",
            dependencies: []),
        .target(
            name: "SwiftLang",
            dependencies: ["Codex"],
			exclude: [
				"Sources/SwiftLang/ArgumentLabel.swift",
				"Sources/SwiftLang/ArrayType.swift",
				"Sources/SwiftLang/Assignment.swift",
				"Sources/SwiftLang/AssignmentOperator.swift",
				"Sources/SwiftLang/AssociatedType.swift",
				"Sources/SwiftLang/Attribute.swift",
				"Sources/SwiftLang/Available.swift",
				"Sources/SwiftLang/BasicBlock.swift",
				"Sources/SwiftLang/BinaryExpression.swift",
				"Sources/SwiftLang/BinaryOperator.swift",
				"Sources/SwiftLang/Block.swift",
				"Sources/SwiftLang/BooleanLiteral.swift",
				"Sources/SwiftLang/BooleanType.swift",
				"Sources/SwiftLang/BreakStatement.swift",
				"Sources/SwiftLang/CaptureList.swift",
				"Sources/SwiftLang/CastExpression.swift",
				"Sources/SwiftLang/CatchClause.swift",
				"Sources/SwiftLang/CharacterLiteral.swift",
				"Sources/SwiftLang/Class.swift",
				"Sources/SwiftLang/Closure.swift",
				"Sources/SwiftLang/CodeContext.swift",
				"Sources/SwiftLang/CodeVisitor.swift",
				"Sources/SwiftLang/CodeWriter.swift",
				"Sources/SwiftLang/CollectionType.swift",
				"Sources/SwiftLang/Comment.swift",
				"Sources/SwiftLang/Constraint.swift",
				"Sources/SwiftLang/Constructor.swift",
				"Sources/SwiftLang/ContinueStatement.swift",
				"Sources/SwiftLang/DataType.swift",
				"Sources/SwiftLang/DeferStatement.swift",
				"Sources/SwiftLang/Destructor.swift",
				"Sources/SwiftLang/DictionaryType.swift",
				"Sources/SwiftLang/DoStatement.swift",
				"Sources/SwiftLang/Enum.swift",
				"Sources/SwiftLang/EnumValue.swift",
				"Sources/SwiftLang/Expression.swift",
				"Sources/SwiftLang/Extension.swift",
				"Sources/SwiftLang/FallthroughStatement.swift",
				"Sources/SwiftLang/FloatingType.swift",
				"Sources/SwiftLang/ForInStatement.swift",
				"Sources/SwiftLang/Function.swift",
				"Sources/SwiftLang/GenericType.swift",
				"Sources/SwiftLang/GuardStatement.swift",
				"Sources/SwiftLang/IfStatement.swift",
				"Sources/SwiftLang/ImportDirective.swift",
				"Sources/SwiftLang/IntegerLiteral.swift",
				"Sources/SwiftLang/IntegerType.swift",
				"Sources/SwiftLang/Label.swift",
				"Sources/SwiftLang/Literal.swift",
				"Sources/SwiftLang/LocalConstant.swift",
				"Sources/SwiftLang/LocalVariable.swift",
				"Sources/SwiftLang/MemberBinding.swift",
				"Sources/SwiftLang/Method.swift",
				"Sources/SwiftLang/Module.swift",
				"Sources/SwiftLang/NestedType.swift",
				"Sources/SwiftLang/NilLiteral.swift",
				"Sources/SwiftLang/NilType.swift",
				"Sources/SwiftLang/ObjectType.swift",
				"Sources/SwiftLang/ObjectTypeSymbol.swift",
				"Sources/SwiftLang/Package.swift",
				"Sources/SwiftLang/Parameter.swift",
				"Sources/SwiftLang/ParameterDirection.swift",
				"Sources/SwiftLang/Property.swift",
				"Sources/SwiftLang/PropertyAccessor.swift",
				"Sources/SwiftLang/PropertyObserver.swift",
				"Sources/SwiftLang/Protocol.swift",
				"Sources/SwiftLang/RangeOperator.swift",
				"Sources/SwiftLang/RealLiteral.swift",
				"Sources/SwiftLang/ReferenceType.swift",
				"Sources/SwiftLang/SetType.swift",
				"Sources/SwiftLang/SourceFile.swift",
				"Sources/SwiftLang/SourceLocation.swift",
				"Sources/SwiftLang/SourceReference.swift",
				"Sources/SwiftLang/Statement.swift",
				"Sources/SwiftLang/StatementList.swift",
				"Sources/SwiftLang/StringLiteral.swift",
				"Sources/SwiftLang/Struct.swift",
				"Sources/SwiftLang/Subroutine.swift",
				"Sources/SwiftLang/Subscript.swift",
				"Sources/SwiftLang/SwiftCodegen.swift",
				"Sources/SwiftLang/SwitchLabel.swift",
				"Sources/SwiftLang/SwitchSection.swift",
				"Sources/SwiftLang/SwitchStatement.swift",
				"Sources/SwiftLang/SymbolAccessibility.swift",
				"Sources/SwiftLang/TargetValue.swift",
				"Sources/SwiftLang/TextWriter.swift",
				"Sources/SwiftLang/ThrowStatement.swift",
				"Sources/SwiftLang/TryStatement.swift",
				"Sources/SwiftLang/Tuple.swift",
				"Sources/SwiftLang/Typealias.swift",
				"Sources/SwiftLang/TypeCheck.swift",
				"Sources/SwiftLang/TypeParameter.swift",
				"Sources/SwiftLang/TypeSymbol.swift",
				"Sources/SwiftLang/UnaryOperator.swift",
				"Sources/SwiftLang/ValueType.swift",
				"Sources/SwiftLang/Variable.swift",
				"Sources/SwiftLang/VoidType.swift",
				"Sources/SwiftLang/WhileStatement.swift"
			]
		),
        .testTarget(
            name: "CodexTests",
            dependencies: ["Codex"]),
    ]
)
